/**
 * Motion sprites, keyed by pose id. The manifest is GENERATED by
 * `scripts/blender/render_motion.py` (`npm run motion`); this file is
 * the hand-kept access layer `poses/index.ts` merges from.
 */
import type { PoseMotion } from '../types';
import { motionManifest } from './manifest';

export const motionByPose: Record<string, PoseMotion> = motionManifest;

/** Public URLs of every sprite sheet (for offline precaching). */
export function motionUrls(): string[] {
  return Object.values(motionManifest).map((m) => m.sprite);
}
