/**
 * Motion sprites, keyed by pose id. The manifest is GENERATED by
 * `scripts/blender/render_motion.py` (`npm run motion`); this file is
 * the hand-kept access layer `poses/index.ts` merges from. The manifest
 * also holds the hand-off bridges (`bridge:<start>-<end>`), which belong
 * to no posture: `bridgeFor` reaches them.
 */
import type { PoseMotion, Position } from '../types';
import { motionManifest } from './manifest';

export const motionByPose: Record<string, PoseMotion> = motionManifest;

/** The bridge sheet from one body position to another (undefined for none, or the same position). */
export function bridgeFor(from: Position, to: Position): PoseMotion | undefined {
  if (from === to) return undefined;
  return motionManifest[`bridge:${from}-${to}`];
}

/** Public URLs of every sprite sheet — layer sheets and bridges included (for offline precaching). */
export function motionUrls(): string[] {
  return Object.values(motionManifest).flatMap((m) =>
    [m.sprite, m.guides, m.ghost].filter((u): u is string => Boolean(u)),
  );
}
