import { muscles } from '../data';
import type { MuscleGroup, MuscleId } from '../data';
import type { KeyboardEvent } from 'react';
import './BodyMap.css';

export type MuscleHighlight = 'strengthens' | 'stretches';

export interface BodyMapProps {
  /** muscle id → how to tint that region */
  highlights?: Partial<Record<MuscleId, MuscleHighlight>>;
  /** currently selected muscle (strong emphasis + ring) */
  selected?: MuscleId | null;
  /** when provided, regions become clickable/keyboard-focusable */
  onSelect?: (id: MuscleId) => void;
  /** which figure(s) to render */
  view?: 'front' | 'back' | 'both';
  /** pixel height of each figure */
  height?: number;
}

/* ------------------------------------------------------------------ geometry
 * Everything is drawn in a 0 0 120 260 viewBox, centered on x = 60.
 * Paired regions are authored for the viewer-right side only and the
 * left side is generated by mirroring across x = 60, so the two sides
 * always match exactly. Path strings use ONLY absolute `M x y`,
 * `C x1 y1 x2 y2 x y` and `Z` commands with single-space separated
 * numbers — the tiny mirror() parser below depends on that format.
 */

const VIEW_W = 120;
const VIEW_H = 260;

const fmt = (n: number) => String(Math.round(n * 100) / 100);

/** Mirror an M/C/Z path across the vertical centerline x = 60. */
function mirror(d: string): string {
  let isX = true;
  return d
    .split(' ')
    .map((token) => {
      if (token === 'M' || token === 'C') {
        isX = true;
        return token;
      }
      if (token === 'Z') return token;
      const out = isX ? fmt(VIEW_W - Number(token)) : token;
      isX = !isX;
      return out;
    })
    .join(' ');
}

/** Author the right side, get both sides as one path (two subpaths). */
const sym = (d: string) => `${d} ${mirror(d)}`;

/* One continuous outline: up the left neck, around the head, down the
 * right side (arm slightly away from the torso, around the hand), down
 * the right leg, around the foot, up between the legs, and back up the
 * left side. Shared by the front and back figures. */
const SILHOUETTE =
  'M 53 41 ' +
  'C 55 37 55.8 34 55.8 30.5 C 51 28.5 48 24.5 48 18.5 C 48 10.4 53 4.8 60 4.8 ' +
  'C 67 4.8 72 10.4 72 18.5 C 72 24.5 69 28.5 64.2 30.5 C 64.2 34 65 37 67 41 ' +
  'C 73 43 80 44.5 84.5 48.5 C 88 51.5 89.5 55 90 60 C 91.5 71 93 84 94.5 97 ' +
  'C 96 109 97.5 120 98.3 130 C 100 134 100.5 138 100.3 142 C 100.2 146 99 149.5 96.5 149.3 ' +
  'C 94 149 92.8 146 92.7 142.5 C 92.6 139 92.3 136 91.8 132 C 90 120 88.8 110 87.6 99 ' +
  'C 86 88 83.5 76 81.5 66 C 82.3 70 82.6 76 81.6 84 C 80 92 77 97 76.4 103 ' +
  'C 76 110 79.5 117 81.3 124 C 82.6 130 82 136 80.8 143 C 79.6 150 77.6 158 75.8 166 ' +
  'C 74.6 172 74 176 74.3 181 C 75.2 186 75.6 191 75.3 196 C 74.6 206 72.4 216 70.3 224 ' +
  'C 69.6 228 69.4 232 70.3 236 C 71.4 240 72.6 243 73.2 246 C 73.4 248.6 71 249.4 68 249.4 ' +
  'C 65.5 249.4 63.2 248.6 62.9 246.4 C 62.7 243 62.7 240 62.8 237 C 62.9 232 62.7 228 62.5 224 ' +
  'C 62.1 214 61.9 205 62.3 197 C 62.7 190 63.2 184 63.3 179 C 63.4 172 62.6 163 61.9 156 ' +
  'C 61.3 150 60.5 145 60 141.5 ' +
  'C 59.5 145 58.7 150 58.1 156 C 57.4 163 56.6 172 56.7 179 C 56.8 184 57.3 190 57.7 197 ' +
  'C 58.1 205 57.9 214 57.5 224 C 57.3 228 57.1 232 57.2 237 C 57.3 240 57.3 243 57.1 246.4 ' +
  'C 56.8 248.6 54.5 249.4 52 249.4 C 49 249.4 46.6 248.6 46.8 246 C 47.4 243 48.6 240 49.7 236 ' +
  'C 50.6 232 50.4 228 49.7 224 C 47.6 216 45.4 206 44.7 196 C 44.4 191 44.8 186 45.7 181 ' +
  'C 46 176 45.4 172 44.2 166 C 42.4 158 40.4 150 39.2 143 C 38 136 37.4 130 38.7 124 ' +
  'C 40.5 117 44 110 43.6 103 C 43 97 40 92 38.4 84 C 37.4 76 37.7 70 38.5 66 ' +
  'C 36.5 76 34 88 32.4 99 C 31.2 110 30 120 28.2 132 C 27.7 136 27.4 139 27.3 142.5 ' +
  'C 27.2 146 26 149 23.5 149.3 C 21 149.5 19.8 146 19.7 142 C 19.5 138 20 134 21.7 130 ' +
  'C 22.5 120 24 109 25.5 97 C 27 84 28.5 71 30 60 C 30.5 55 32 51.5 35.5 48.5 ' +
  'C 40 44.5 47 43 53 41 Z';

/* --- shared (front + back) --- */
const NECK =
  'M 56.4 32.5 C 57.6 34.4 62.4 34.4 63.6 32.5 C 64 35.6 64.8 38.6 66 41 ' +
  'C 62 42.6 58 42.6 54 41 C 55.2 38.6 56 35.6 56.4 32.5 Z';
const DELTOIDS = sym(
  'M 82.5 49.5 C 85.6 51 88.2 54 89.4 58.4 C 90 61.4 90 64.4 89.4 67 ' +
    'C 87 65.8 84.8 63.6 83.4 60.4 C 82.4 57 82.1 53.2 82.5 49.5 Z',
);
/* biceps on the front figure, triceps on the back figure */
const UPPER_ARMS = sym(
  'M 85 70 C 87.2 71 89 73 90 75.8 C 91 81.4 91.7 87 92 92.2 ' +
    'C 90.6 94 88.7 94.2 87.3 92.8 C 86.1 86.6 85.2 80.2 84.8 73.8 C 84.7 72.4 84.8 71 85 70 Z',
);
const FOREARMS = sym(
  'M 89.6 102.5 C 91.6 103 93.4 104.2 94.4 106.4 C 95.6 113.2 96.5 120.6 96.9 127.4 ' +
    'C 95.6 129.4 93.5 129.7 92 128.3 C 91 121 90.1 113 89.4 105.4 C 89.3 104.2 89.4 103.2 89.6 102.5 Z',
);
const FEET = sym(
  'M 64 231.5 C 65.8 230.6 67.7 230.8 69 232 C 69.9 236.2 70.8 240.2 71.6 244 ' +
    'C 69.8 246.2 66 246.4 64.4 244.6 C 64 240.4 63.9 236 64 231.5 Z',
);

/* --- front only --- */
const PECTORALS = sym(
  'M 61.8 52.5 C 66.8 52 72.4 53.6 76.4 56.6 C 77.8 60.4 77.9 65 76.2 68.8 ' +
    'C 73.2 72.6 67.4 73.8 63.4 71.4 C 62.2 67.8 61.6 63.6 61.6 59.2 C 61.6 56.8 61.7 54.6 61.8 52.5 Z',
);
const DIAPHRAGM =
  'M 47 82 C 51.5 76.5 55.8 74 60 74 C 64.2 74 68.5 76.5 73 82 ' +
  'C 72.3 84.5 71 86.3 69.2 87.3 C 66.2 83.9 63.1 82.3 60 82.3 ' +
  'C 56.9 82.3 53.8 83.9 50.8 87.3 C 49 86.3 47.7 84.5 47 82 Z';
const ABDOMINALS =
  'M 54.8 85.5 C 58 84.3 62 84.3 65.2 85.5 C 65.9 97 65.9 109 65.1 120.5 ' +
  'C 61.7 123 58.3 123 54.9 120.5 C 54.1 109 54.1 97 54.8 85.5 Z';
const OBLIQUES_FRONT = sym(
  'M 68.6 89 C 71.2 89.4 74 90.4 76.2 92.2 C 75.4 97.6 74.9 103.2 75.2 108.8 ' +
    'C 73.1 108 70.9 106.4 69.4 104 C 68.4 99 68.2 94 68.6 89 Z',
);
const HIP_FLEXORS = sym(
  'M 66.5 113.5 C 69 115.2 71.4 117.8 73.1 121.2 C 74.6 125.6 75.6 130.2 76 135 ' +
    'C 74.2 137 71.7 137.2 69.8 135.6 C 68.2 130 66.9 124.4 66 118.7 C 65.8 116.7 65.9 114.9 66.5 113.5 Z',
);
const QUADRICEPS = sym(
  'M 66.8 141 C 70.2 139.8 74 140.2 77 142.2 C 77.8 149.8 77.2 157.4 75.4 164.6 ' +
    'C 74.7 169.6 74 174 73.6 178 C 71.2 180.2 68.4 180.4 66.4 178.6 ' +
    'C 65.8 171.4 65.5 164 65.5 156.8 C 65.5 151.4 65.9 146.2 66.8 141 Z',
);
const ADDUCTORS = sym(
  'M 62 145.5 C 63.2 144.4 64.4 144.4 65.1 145.8 C 65.4 150.6 65.3 155.6 64.9 160.6 ' +
    'C 64.3 162.6 63.2 162.7 62.7 160.8 C 62.2 155.6 62.1 150.4 62 145.5 Z',
);

/* --- back only --- */
const TRAPEZIUS =
  'M 54.5 44.5 C 58 46.2 62 46.2 65.5 44.5 C 70.5 45.8 76.5 46.8 80.5 49.5 ' +
  'C 74.5 53.5 68.8 56.5 65.2 61.5 C 63.2 68.5 61.8 76 60 83.5 ' +
  'C 58.2 76 56.8 68.5 54.8 61.5 C 51.2 56.5 45.5 53.5 39.5 49.5 C 43.5 46.8 49.5 45.8 54.5 44.5 Z';
const LATS = sym(
  'M 67.2 65 C 71.6 66.4 76.4 68.8 80 72 C 80.7 78.2 80 84.6 78.4 90.2 ' +
    'C 77.2 92.8 75.4 94.6 73.2 95.4 C 70.6 93.4 68.6 90.4 67.7 86.4 C 67 79.4 66.9 72.2 67.2 65 Z',
);
const ERECTOR_SPINAE = sym(
  'M 61.6 88 C 62.9 87.3 64.3 87.3 65.2 88.2 C 65.6 93 65.7 98 65.6 103 ' +
    'C 65.5 107.6 65.2 112 64.7 116.2 C 63.5 117.4 62.3 117.4 61.5 116.2 ' +
    'C 61.1 111.6 60.9 107 60.9 102.2 C 60.9 97.4 61.1 92.6 61.6 88 Z',
);
const OBLIQUES_BACK = sym(
  'M 68.4 98.5 C 70.9 99 73.3 100 75 102 C 74.5 106.4 74.4 110.8 74.9 115.2 ' +
    'C 72.8 114.6 70.6 113.2 69.1 111 C 68.2 106.8 68 102.6 68.4 98.5 Z',
);
const GLUTES = sym(
  'M 61 121 C 65.6 119 71.2 119.2 75.8 121.6 C 78.6 124.6 80 128.8 79.9 133.4 ' +
    'C 79.8 138.4 77.6 142.4 73.8 144.6 C 69.4 146.6 64.6 145.8 62.2 142.6 ' +
    'C 61 138.6 60.6 133.6 60.7 128.4 C 60.8 125.8 60.9 123.3 61 121 Z',
);
const HAMSTRINGS = sym(
  'M 66.8 149.5 C 70 148.4 73.6 148.8 76.2 150.6 C 76.8 156.2 76 162 74.5 168 ' +
    'C 73.8 172.6 73.4 177 73.2 181.4 C 70.9 183.6 68.3 183.8 66.5 182.2 ' +
    'C 65.9 175.6 65.6 168.8 65.7 162.4 C 65.8 158 66.1 153.7 66.8 149.5 Z',
);
const CALVES = sym(
  'M 64.6 189 C 67.2 187.6 70.4 188 72.6 190 C 73.7 195 73.9 200.4 73.3 206 ' +
    'C 72.7 212.4 71.4 218 69.6 222.4 C 67.6 223.8 65.4 223.6 64.1 221.8 ' +
    'C 63.5 214.8 63.2 207.6 63.4 200.6 C 63.5 196.6 63.9 192.6 64.6 189 Z',
);

const REGION_PATHS: Record<MuscleId, { front?: string; back?: string }> = {
  'neck': { front: NECK, back: NECK },
  'trapezius': { back: TRAPEZIUS },
  'deltoids': { front: DELTOIDS, back: DELTOIDS },
  'biceps': { front: UPPER_ARMS },
  'triceps': { back: UPPER_ARMS },
  'forearms': { front: FOREARMS, back: FOREARMS },
  'pectorals': { front: PECTORALS },
  'lats': { back: LATS },
  'erector-spinae': { back: ERECTOR_SPINAE },
  'abdominals': { front: ABDOMINALS },
  'obliques': { front: OBLIQUES_FRONT, back: OBLIQUES_BACK },
  'diaphragm': { front: DIAPHRAGM },
  'hip-flexors': { front: HIP_FLEXORS },
  'glutes': { back: GLUTES },
  'quadriceps': { front: QUADRICEPS },
  'hamstrings': { back: HAMSTRINGS },
  'adductors': { front: ADDUCTORS },
  'calves': { back: CALVES },
  'ankles-feet': { front: FEET, back: FEET },
};

/* ------------------------------------------------------------------ component */

type FigureSide = 'front' | 'back';

function musclesFor(side: FigureSide): MuscleGroup[] {
  return muscles.filter(
    (m) => (m.view === 'both' || m.view === side) && REGION_PATHS[m.id]?.[side],
  );
}

function describe(
  side: FigureSide,
  shown: MuscleGroup[],
  highlights: Partial<Record<MuscleId, MuscleHighlight>>,
): string {
  const list = (kind: MuscleHighlight) =>
    shown.filter((m) => highlights[m.id] === kind).map((m) => m.name);
  const strengthens = list('strengthens');
  const stretches = list('stretches');
  const label = side === 'front' ? 'Front' : 'Back';
  const parts: string[] = [];
  if (strengthens.length) parts.push(`strengthens ${strengthens.join(', ')}`);
  if (stretches.length) parts.push(`stretches ${stretches.join(', ')}`);
  return parts.length ? `${label} of body: ${parts.join('; ')}` : `${label} of body`;
}

export function BodyMap({
  highlights = {},
  selected = null,
  onSelect,
  view = 'both',
  height = 300,
}: BodyMapProps) {
  const sides: FigureSide[] = view === 'both' ? ['front', 'back'] : [view];
  const interactive = onSelect !== undefined;
  const width = Math.round((height * VIEW_W) / VIEW_H);

  return (
    <div className={`bodymap${interactive ? ' bodymap--interactive' : ''}`}>
      {sides.map((side) => {
        const shown = musclesFor(side);
        return (
          <div key={side} className="bodymap-figure">
            <svg
              className="bodymap-svg"
              viewBox={`0 0 ${VIEW_W} ${VIEW_H}`}
              width={width}
              height={height}
              role={interactive ? 'group' : 'img'}
              aria-label={
                interactive
                  ? `${side === 'front' ? 'Front' : 'Back'} of body: choose a muscle group`
                  : describe(side, shown, highlights)
              }
            >
              <path className="bodymap-silhouette" d={SILHOUETTE} aria-hidden="true" />
              {shown.map((m) => {
                const d = REGION_PATHS[m.id][side];
                if (!d) return null;
                const hl = highlights[m.id];
                const isSelected = selected === m.id;
                const handleKey = (e: KeyboardEvent<SVGPathElement>) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    onSelect?.(m.id);
                  }
                };
                return (
                  <path
                    key={m.id}
                    d={d}
                    className={`bodymap-region${isSelected ? ' bodymap-region--selected' : ''}`}
                    data-hl={hl}
                    role={interactive ? 'button' : undefined}
                    tabIndex={interactive ? 0 : undefined}
                    aria-pressed={interactive ? isSelected : undefined}
                    onClick={interactive ? () => onSelect?.(m.id) : undefined}
                    onKeyDown={interactive ? handleKey : undefined}
                  >
                    <title>{m.name}</title>
                  </path>
                );
              })}
            </svg>
            {view === 'both' && (
              <span className="bodymap-figure-label" aria-hidden="true">
                {side === 'front' ? 'Front' : 'Back'}
              </span>
            )}
          </div>
        );
      })}
    </div>
  );
}
