/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with: node scripts/generate-voice.mjs
 * Maps every spoken cue text (see cue-script.ts) to its recorded clip.
 */
export const voiceClips: Record<string, string> = {
  "Begin exactly as in Tree: right foot drawn up toward the left hip crease, folded knee pressing down.": "/voice/fa7a6b55725f.ogg",
  "Blowing in Firm Pose.": "/voice/d94d43f4467b.ogg",
  "Both knees — pull, and let the lower back open.": "/voice/9fb3cb4d879b.ogg",
  "Both knees — wrap the arms around the shins and pull everything in.": "/voice/10686df8d412.ogg",
  "Both legs together — grip the toes and stretch the whole body forward.": "/voice/67ccd1b830fe.ogg",
  "Both legs — grip the toes, pull, and stretch forward.": "/voice/8cb215fb4b58.ogg",
  "Both legs — press the arms down and lift everything together.": "/voice/ed485655c08b.ogg",
  "Change knees — hug the left knee down to the chest.": "/voice/3465cf468f35.ogg",
  "Change knees.": "/voice/a17585bc3f0f.ogg",
  "Change legs — head to the left knee.": "/voice/34a9bc5db53c.ogg",
  "Change legs — left leg up, hip stays down.": "/voice/8b86364c9822.ogg",
  "Change legs.": "/voice/6793c8b734f3.ogg",
  "Come up and fold forward — grip the heels from behind and pull the body against the legs.": "/voice/4f5a1216c641.ogg",
  "Come up slowly — and over to the left side.": "/voice/fd0d61736690.ogg",
  "Come up — and bend back one more time.": "/voice/c2ee0b66eb08.ogg",
  "Come up — and to the left.": "/voice/15987a89323a.ogg",
  "Come up — head back, arms back, hips forward, and bend backward.": "/voice/b426b67391d5.ogg",
  "Come up — rise to the very top of the toes, and sit again.": "/voice/0c9b2685e363.ogg",
  "Fix all your weight into one leg and lock that knee — thigh contracted, kneecap lifted, the leg one solid piece from hip to floor.": "/voice/822761b2ac4b.ogg",
  "Fold forward again — grip the heels, pull, and lay the body flat on the legs.": "/voice/f83139f92257.ogg",
  "From a wide stance — about four feet — raise the arms to shoulder height, palms down, in one line.": "/voice/90e7c70d635a.ogg",
  "From standing, sweep the arms overhead and press the palms flat together, thumbs crossed.": "/voice/26a74973bd8f.ogg",
  "Heels up, knees together — lower down in slow motion.": "/voice/23936d2953c9.ogg",
  "Kneel on the floor with your knees together and your feet apart, alongside your hips.": "/voice/68c5cccc5d19.ogg",
  "Kneel upright with the knees and feet about six inches apart, toes pointing straight back.": "/voice/c5635d943da2.ogg",
  "Kneel with your knees and feet together and sit back on your heels.": "/voice/1b098c4f45d3.ogg",
  "Knees together — slow motion down, slow motion up.": "/voice/45c15bf3e6e6.ogg",
  "Lie face down with the chin reaching forward along the floor.": "/voice/c915a48cf66e.ogg",
  "Lie flat on your back with the legs extended along the floor.": "/voice/e9f945e5d8e1.ogg",
  "Lie flat on your back with the legs extended and the heels together.": "/voice/4b947275f6a8.ogg",
  "Lie on your abdomen and bend both knees.": "/voice/bb2e2db9d46d.ogg",
  "Lie on your abdomen with your chin stretched forward on the floor.": "/voice/20ecf1507e89.ogg",
  "Lie on your stomach, chin on the floor, legs together — hips, thighs, and the tops of the feet all pressing down.": "/voice/90f8adb69560.ogg",
  "Lying on your back, straighten both legs and flex the feet back toward your face.": "/voice/725d5c72ac1c.ogg",
  "Other side — come down slowly, spine tall, hands floating to prayer.": "/voice/739194f0d754.ogg",
  "Other side — grip the left ankle, right arm up.": "/voice/f4f271e8d0ae.ogg",
  "Other side — left arm under, left leg over the top.": "/voice/6e7c49b93c96.ogg",
  "Other side — left knee bends, arms tip the other way, eyes on the top hand.": "/voice/5fbc52f9fc56.ogg",
  "Other side — pivot the feet, square off over the left leg, and round down.": "/voice/c1b7866415e2.ogg",
  "Other side — stand on the right leg, lock the knee, and pick up the left foot.": "/voice/4ad73adffb66.ogg",
  "Other side — stand tall on the right leg, left foot up, palms to prayer.": "/voice/90b0f84b991f.ogg",
  "Other side — step forward and tip, one straight line.": "/voice/26bb59baa747.ogg",
  "Other side — ten seconds, everything you have.": "/voice/18708c8ee8e7.ogg",
  "Other side — twist to the left, look over the left shoulder.": "/voice/b30ea577ddd3.ogg",
  "Other side.": "/voice/286af4ee31f4.ogg",
  "Posture 10. Standing Separate Leg Head to Knee Pose.": "/voice/9553abb562ee.ogg",
  "Posture 11. Tree Pose.": "/voice/cc560706d206.ogg",
  "Posture 12. Toe Stand Pose.": "/voice/8c4f20b7690a.ogg",
  "Posture 13. Dead Body Pose.": "/voice/e8997f0a0cd4.ogg",
  "Posture 14. Wind-Removing Pose.": "/voice/4e1e757e5547.ogg",
  "Posture 15. Sit-Up.": "/voice/e841fbc2480a.ogg",
  "Posture 16. Cobra Pose.": "/voice/3e3b30f964be.ogg",
  "Posture 17. Locust Pose.": "/voice/db03fa598cff.ogg",
  "Posture 18. Full Locust Pose.": "/voice/9aff3b684e55.ogg",
  "Posture 19. Bow Pose.": "/voice/2b406de5d4e5.ogg",
  "Posture 2. Half Moon Pose with Hands to Feet Pose.": "/voice/251b73d06074.ogg",
  "Posture 20. Fixed Firm Pose.": "/voice/d241f12e0a05.ogg",
  "Posture 21. Half Tortoise Pose.": "/voice/b0f9d08510af.ogg",
  "Posture 22. Camel Pose.": "/voice/5039ae1434a0.ogg",
  "Posture 23. Rabbit Pose.": "/voice/ea05156197df.ogg",
  "Posture 24. Head to Knee Pose with Stretching Pose.": "/voice/877598970fcc.ogg",
  "Posture 25. Spine-Twisting Pose.": "/voice/8737997dae84.ogg",
  "Posture 3. Awkward Pose.": "/voice/f4912462ed75.ogg",
  "Posture 4. Eagle Pose.": "/voice/1988d00eb89f.ogg",
  "Posture 5. Standing Head to Knee Pose.": "/voice/8a6abf8bf458.ogg",
  "Posture 6. Standing Bow Pulling Pose.": "/voice/df006ca8a3ab.ogg",
  "Posture 7. Balancing Stick Pose.": "/voice/4d4e4704414b.ogg",
  "Posture 8. Standing Separate Leg Stretching Pose.": "/voice/b260e9628a3f.ogg",
  "Posture 9. Triangle Pose.": "/voice/0a56cb51e1fa.ogg",
  "Raise both arms overhead and press the palms together, crossing the thumbs, arms hugging the ears.": "/voice/0fe0c155e257.ogg",
  "Roll over onto the belly, chin forward on the towel.": "/voice/aa9626480641.ogg",
  "Second set — a little faster. Sixty more.": "/voice/f5aae07f2347.ogg",
  "Second set — arms out, and sit down.": "/voice/509697581470.ogg",
  "Second set — arms up, stretch, and over to the right.": "/voice/83c609ed99cc.ogg",
  "Second set — chin to chest, forehead to the knee. Right side.": "/voice/c73e9dc24fe0.ogg",
  "Second set — everything lifts at once, look up.": "/voice/1652e2a97db0.ogg",
  "Second set — fold forward, forehead down, hips on the heels.": "/voice/d24dd658eb9e.ogg",
  "Second set — grip the ankles, kick, and look up.": "/voice/1df67ab6aa9f.ogg",
  "Second set — hips forward the whole time, one hand to each heel.": "/voice/51489065a7f8.ogg",
  "Second set — kick back and stretch forward. Right leg.": "/voice/1fe9eb8b7105.ogg",
  "Second set — only as deep as the knees allow, arms overhead on the floor.": "/voice/6eb3f79b7afc.ogg",
  "Second set — palms down, chest up, legs heavy on the floor.": "/voice/e9858bcc69c6.ogg",
  "Second set — right knee to the chest.": "/voice/84ffb6c1abf9.ogg",
  "Second set — right leg again, thirty seconds. Standing knee locked.": "/voice/830ec3b1019f.ogg",
  "Second set — right leg, head to the knee.": "/voice/91e720382484.ogg",
  "Second set — right leg, left leg, then both legs together.": "/voice/9178cce52270.ogg",
  "Second set — roll forward like a wheel, hips high, arms pulling.": "/voice/d94df392f908.ogg",
  "Second set — sink the hips low, arms one straight line. Right side.": "/voice/99bc20b4b1ea.ogg",
  "Second set — step forward, everything comes down together.": "/voice/772b6a6b1bc2.ogg",
  "Second set — step out wide, fold from the hips, and pull the forehead toward the floor.": "/voice/9fba212ff605.ogg",
  "Second set — ten more full breaths. Elbows high on the inhale, head back on the exhale.": "/voice/61263dfb1e13.ogg",
  "Second set — wrap the arms, sit down, and wrap the legs. Right side.": "/voice/c00d32d4e0ae.ogg",
  "Sit and bend the left knee down to the floor, drawing the left heel beside the right hip.": "/voice/b65bb0e7db6c.ogg",
  "Sit and extend the right leg out at about forty-five degrees; bend the left knee and place the left sole against the right inner thigh.": "/voice/5d5b100f5e76.ogg",
  "Sit on your heels in Vajrasana — spine tall, shoulders relaxed, chest lifted.": "/voice/90c0402c3fb8.ogg",
  "Sit on your heels, then reach back and grip each heel firmly — thumbs on the outside, fingers on the inside.": "/voice/6897da132998.ogg",
  "Sit-up — arms overhead, cross the thumbs, double exhale, and dive for the toes.": "/voice/2e8eda70ac90.ogg",
  "Sit-up.": "/voice/f5d0cf620a7a.ogg",
  "Stand tall and shift your full weight onto the left leg, locking the knee.": "/voice/63dba782a3b8.ogg",
  "Stand tall, pour your weight into the left foot, and fix your gaze on one unmoving point ahead.": "/voice/caeb1b0a0520.ogg",
  "Stand with feet together, heels and toes touching.": "/voice/49a584eb7633.ogg",
  "Stand with feet together; sweep the arms up sideways over the head and interlace the fingers, releasing the index fingers into a steeple grip.": "/voice/b40867b593fd.ogg",
  "Standing Deep Breathing.": "/voice/0041ac13f891.ogg",
  "Step or lightly hop the feet wide apart — roughly four feet, toes turned slightly inward.": "/voice/854954ede465.ogg",
  "Step the feet hip-width apart, toes and heels in two parallel lines.": "/voice/2a296d45386a.ogg",
  "Swing the arms out wide, then cross the right arm under the left at the elbows.": "/voice/7919340c84d3.ogg",
  "Twenty-second savasana.": "/voice/2a8a80e4c8d4.ogg",
  "Up on the toes — and sit.": "/voice/c0de4380397e.ogg",
};
