/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with: node scripts/generate-voice.mjs
 * Maps every spoken cue text (see cue-script.ts) to its recorded clip.
 */
export const voiceClips: Record<string, string> = {
  "After the left side, hug both knees in together, wrapping the arms across the shins to hold opposite elbows if you can reach them.": "/voice/87417debd13d.ogg",
  "Aim the face for the shins and hug the elbows in behind the calves; the fold gets its depth from patience, not momentum.": "/voice/d04e5f96456e.ogg",
  "Aim the forehead for the floor between the feet — touching is the destination, not the requirement.": "/voice/f719d48e71dd.ogg",
  "Aim the thigh at the shoulder on its own side so it presses beside the ribcage — that is what compresses the colon, right side first, following the direction of digestion.": "/voice/eae7efc82734.ogg",
  "Arms stay straight as arrows, biceps beside the ears, palms sealed together.": "/voice/ad1d410f4f75.ogg",
  "Balance lives on the ball of the foot — the lifted heel becomes the stool you sit on.": "/voice/87db20f8964f.ogg",
  "Balance the whole body on the abdomen, and with each breath try to fly a little higher.": "/voice/ef8142840bb3.ogg",
  "Begin exactly as in Tree: right foot drawn up toward the left hip crease, folded knee pressing down.": "/voice/fa7a6b55725f.ogg",
  "Begin kicking the right leg back and up as the left arm and upper body stretch forward.": "/voice/cc68b5f99f2c.ogg",
  "Bend the right knee and draw the thigh toward the chest.": "/voice/8e3fc46a82be.ogg",
  "Bend the right knee and lift the right foot, placing the sole high against the left inner thigh — heel working toward the hip crease, like a half lotus resting against the leg.": "/voice/6f2f900a3c5f.ogg",
  "Bend the right knee and sink the hips until the right thigh is parallel to the floor, knee stacked over the ankle.": "/voice/0ffb146b3d85.ogg",
  "Bend the standing knee and fold forward, reaching the fingertips to the floor for balance.": "/voice/6053dfe80812.ogg",
  "Blowing in Firm Pose.": "/voice/d94d43f4467b.ogg",
  "Both hips stay level and heavy on the arms; do not roll toward the lifting side.": "/voice/ee6b5959716c.ogg",
  "Both knees locked and both elbows locked throughout — all the movement comes from the waist, not the arms or hips.": "/voice/69a08b680018.ogg",
  "Both knees — pull, and let the lower back open.": "/voice/9fb3cb4d879b.ogg",
  "Both knees — wrap the arms around the shins and pull everything in.": "/voice/10686df8d412.ogg",
  "Both legs are working — one locked to stand on, one locked in the air; neither gets to rest.": "/voice/b2ecdbebd474.ogg",
  "Both legs together — grip the toes and stretch the whole body forward.": "/voice/67ccd1b830fe.ogg",
  "Both legs — grip the toes, pull, and stretch forward.": "/voice/8cb215fb4b58.ogg",
  "Both legs — press the arms down and lift everything together.": "/voice/ed485655c08b.ogg",
  "Bring the left arm over the outside of the right knee, then reach down and take hold of the left knee — the arm presses against the raised leg while the hand grips the down knee.": "/voice/8b7d0c393eb4.ogg",
  "Bring the spine upright, then float the hands off the floor one at a time and press the palms together at the chest.": "/voice/814508acf659.ogg",
  "Bring your chin to the floor and let your knees separate to about hip width.": "/voice/996234d1bd97.ogg",
  "Bring your legs together, knees straight, toes pointed.": "/voice/77b3fff9dcda.ogg",
  "Change knees — hug the left knee down to the chest.": "/voice/3465cf468f35.ogg",
  "Change knees.": "/voice/a17585bc3f0f.ogg",
  "Change legs — head to the left knee.": "/voice/34a9bc5db53c.ogg",
  "Change legs — left leg up, hip stays down.": "/voice/8b86364c9822.ogg",
  "Change legs.": "/voice/6793c8b734f3.ogg",
  "Chin toward the shoulder, eyes on the top hand — the gaze completes the line.": "/voice/1d9abc1f8d81.ogg",
  "Come out the way you went in — slowly, chin tucked, unrolling the spine from the bottom up.": "/voice/cc035ed8321a.ogg",
  "Come up and fold forward — grip the heels from behind and pull the body against the legs.": "/voice/4f5a1216c641.ogg",
  "Come up only to the navel; the belly button stays on the floor. This is a half cobra, and that is the point — it isolates the lumbar spine.": "/voice/96a8098cc841.ogg",
  "Come up slowly — and over to the left side.": "/voice/fd0d61736690.ogg",
  "Come up the same way you went down — straight spine, no hands pushing off the floor.": "/voice/03b763af0dc1.ogg",
  "Come up — and bend back one more time.": "/voice/c2ee0b66eb08.ogg",
  "Come up — and to the left.": "/voice/15987a89323a.ogg",
  "Come up — head back, arms back, hips forward, and bend backward.": "/voice/b426b67391d5.ogg",
  "Come up — rise to the very top of the toes, and sit again.": "/voice/0c9b2685e363.ogg",
  "Coming out, retrace your steps — elbows first, then up, never twisting sideways off the legs.": "/voice/c0d0e9d0bb5c.ogg",
  "Completely natural, unmanaged breathing. After twelve postures of directed breath, you do nothing at all — just watch it slow down by itself.": "/voice/eb363720ae0d.ogg",
  "Dive forward, take hold of the big toes, and pull, reaching the elbows toward the floor and the forehead toward the knees.": "/voice/eec3fe62b342.ogg",
  "Do not hold your breath, no matter how intense it gets — keep a strong, steady breath moving through the nose for the full ten seconds.": "/voice/55266db1355e.ogg",
  "Do not inhale on purpose — release the belly and the in-breath happens by itself.": "/voice/e756b25edb11.ogg",
  "Each exhale is a sharp blow out through the lips, and each one snaps the belly button back toward the spine.": "/voice/b4b2537c52b6.ogg",
  "Elbows bend down toward the floor on either side of the calf — use the arms to deepen the fold, not to yank.": "/voice/7bdf91f6d721.ogg",
  "Elbows stay bent and pinned to your sides; do not press up into straight arms.": "/voice/126e49b5a7c2.ogg",
  "Engage the quadriceps to invite the hamstrings to release.": "/voice/ea3a238edc8e.ogg",
  "Everything lifts together — chest, arms, and legs rise as one piece, like a plane leaving the runway.": "/voice/18f5d63e02be.ogg",
  "Exhale as you bend into the lunge, then keep a strong, steady breath through the nose — this posture asks for a lot of oxygen, so never let the breath stall.": "/voice/e67cc865c8ae.ogg",
  "Exhale as you round down, then keep the breath slow and even inside the compression — the tucked chin makes each breath naturally smaller, so let it be calm rather than strained.": "/voice/eab204e6c466.ogg",
  "Exhale by the mouth for six counts, dropping the head back and bringing elbows, wrists, and forearms together in front of the face.": "/voice/2c286e7ab8a9.ogg",
  "Exit with the same control you entered with — rising slowly back to Tree is part of the posture.": "/voice/94b16dadab20.ogg",
  "Eyes open, body still — only the arms, head, and breath are moving.": "/voice/13b386d559ee.ogg",
  "Eyes stay open and soft: this is awake stillness, not sleep.": "/voice/87e50a4fa445.ogg",
  "Feed the arms, one at a time, straight under the body — palms flat and facing down beneath the hips.": "/voice/909b90c2c378.ogg",
  "Feel the heartbeat slow on its own — that descent is the work happening.": "/voice/a04e3d851223.ogg",
  "Feeling flushed, shaky, or unexpectedly emotional is common in this posture — the whole front body is opening. Let it move through you and stay with the breath.": "/voice/f71eb8aa3d30.ogg",
  "Feet stay flexed toward your face — stretch out through the heels as you pull the toes back.": "/voice/6567d4ef9a94.ogg",
  "Fill the lungs completely on every inhale; empty them completely on every exhale.": "/voice/74cb03da1fb2.ogg",
  "Finally fold forward, take hold of the heels from behind with the palms under the feet, and pull the body flat against the legs.": "/voice/f6033b7c0ed1.ogg",
  "Fix all your weight into one leg and lock that knee — thigh contracted, kneecap lifted, the leg one solid piece from hip to floor.": "/voice/822761b2ac4b.ogg",
  "Fix the eyes on one point straight ahead; the posture balances on the gaze as much as the standing foot.": "/voice/824855d184f0.ogg",
  "Fix your eyes on one spot ahead — the gaze steadies the balance more than the feet do.": "/voice/588bbbc95aa1.ogg",
  "Fix your gaze on a spot on the floor about four feet ahead — it stays there for the entire posture.": "/voice/bd528462631e.ogg",
  "Fix your gaze on one point ahead of you before anything starts to move.": "/voice/97e6aa605b61.ogg",
  "Flex the lifted foot hard and kick the heel forward as if pressing it flat into a wall.": "/voice/090874e3edb9.ogg",
  "Fold forward again — grip the heels, pull, and lay the body flat on the legs.": "/voice/f83139f92257.ogg",
  "Fold from the hips, not the waist — send your sitting bones up toward the ceiling as the torso drops.": "/voice/5e1777b980ba.ogg",
  "For the backbend, drop the head back, look behind you, and let arms and torso follow as far back as they will go while the hips press forward.": "/voice/bee1691bb666.ogg",
  "For the final part, press the arms down into the floor and, with one strong inhale, lift both legs together as high as they will go.": "/voice/6c0c2b4e0014.ogg",
  "For the stretching pose, bring both legs together straight in front of you and take hold of the feet or big toes.": "/voice/1edcd8208fef.ogg",
  "Forehead to knee is the posture — contact comes first, a straight leg comes later. Bend the knee until they touch.": "/voice/a702c9fb2713.ogg",
  "From a wide stance — about four feet — raise the arms to shoulder height, palms down, in one line.": "/voice/90e7c70d635a.ogg",
  "From standing, sweep the arms overhead and press the palms flat together, thumbs crossed.": "/voice/26a74973bd8f.ogg",
  "From tailbone to fingertips you are one continuous curve — arms stay with the ears the whole way down and the whole way up.": "/voice/0b64d38d1fd3.ogg",
  "Give the breath back to the body — for the first time in class, no counting and no control.": "/voice/e7625e9e73b6.ogg",
  "Go down the way you would descend a ladder — one stage at a time, never falling backward.": "/voice/75a0385166c6.ogg",
  "Heels up, knees together — lower down in slow motion.": "/voice/23936d2953c9.ogg",
  "Hips stay level and square to the front; do not let the lifted-leg side hitch up.": "/voice/8ee767c976fd.ogg",
  "Hold the foot in place with one hand for as long as you need it.": "/voice/2d383b3e1999.ogg",
  "Holding the foot is not cheating — prayer hands are the destination, not the entry requirement.": "/voice/c20e4e113e30.ogg",
  "Honor the stages: standing locked with the foot in your hands is the complete posture until the kick-out is truly ready.": "/voice/1fb739027d27.ogg",
  "Hug the elbows in against the ribs.": "/voice/9154d80df88b.ogg",
  "If the floor is far away today, walk the hands to the ankles or widen the stance slightly — the stretch is the point, not the touch.": "/voice/d0ee1fcddf6a.ogg",
  "If the knees stay down, lower the shoulders and head to the floor.": "/voice/8d866e2a36d9.ogg",
  "If the low back protests, soften the knees slightly or roll to your side and press up with the hands instead.": "/voice/7b4a49b1aa2d.ogg",
  "If you fall out, step right back in — the posture is built from a thousand attempts.": "/voice/1522492f3663.ogg",
  "In Hands to Feet, pull hard on the heels — the pulling folds you flat — then work the knees toward locked without losing the grip.": "/voice/69442deb8ee0.ogg",
  "In head to knee, the forehead touching the knee matters more than a straight leg — keep the touch and straighten the leg gradually.": "/voice/38de2e499986.ogg",
  "In one motion, sit up — arms swinging forward past the ears toward the toes.": "/voice/80d0b7c6cf6a.ogg",
  "In one motion, tip the entire body forward like a seesaw — arms and torso coming down as the left leg rises behind you.": "/voice/697d59eeb6af.ogg",
  "In part one, lean the upper body back and keep the weight in the heels; the lower you sit, the more the posture gives back.": "/voice/a0ec0f75940b.ogg",
  "In part three, descend like sliding down a wall: spine straight, knees glued together, slow motion the whole way down and the whole way up.": "/voice/e28fb1e22eaa.ogg",
  "In part two, get to the very top of the toes before you sit — the higher the heels, the steadier the balance.": "/voice/b0ef47dbd8a7.ogg",
  "In the backbend, the head goes back first; keep the eyes open, breathe, and push the hips forward to counterbalance.": "/voice/f580934ba956.ogg",
  "In the both-knees part, pull steadily down until you feel the entire lower back flatten and open.": "/voice/36dc28c29f96.ogg",
  "In the side bends, push the hips beyond the line of the body in the opposite direction so the bend deepens evenly along the whole side.": "/voice/8f786fdc807a.ogg",
  "In the stretching pose, lead with the belly onto the thighs, then chest, then head — a long fold, not a collapsed one.": "/voice/7e7b61abca64.ogg",
  "Inhale by the nose for a slow count of six, lifting the elbows up beside the ears like wings.": "/voice/a06768b13693.ogg",
  "Inhale fully as you rise, then hold the posture on mostly full lungs, sipping small breaths through the nose — the lifted chest needs the support of air inside it. Exhale completely as you lower down.": "/voice/bd46742bc64f.ogg",
  "Inhale lying down as the arms reach overhead; exhale as you sit up; then a second, sharper exhale as you grab the toes — the signature double exhale that empties the lungs completely.": "/voice/8ffce72f058f.ogg",
  "Inhale to lengthen the spine long, exhale to fold deeper. Keep a steady, normal breath through the holds — the fold ripens on the exhale.": "/voice/20a81ce5aaa8.ogg",
  "Inhale to lengthen the spine, exhale to fold deeper. Once you are in, keep a slow, even breath — each exhale lets the legs release a little more.": "/voice/6ba2d048d9af.ogg",
  "Inhale to lift each leg, and take a strong inhale before the double-leg lift. During the holds the chest is compressed, so breathe in short, steady sips — never hold the breath entirely.": "/voice/8ec70890f026.ogg",
  "Inhale to lift, then keep the breath moving in short, steady sips — the belly is bearing your weight, so the breath will be shallow, but never hold it.": "/voice/f8e7ad8d69fb.ogg",
  "Inhale to sit taller, exhale to rotate a little further — each breath cycle ratchets the twist deeper. Keep breathing evenly at your edge; never hold the breath in a twist.": "/voice/cec743cab3df.ogg",
  "Interlace all ten fingers a couple of inches below the kneecap.": "/voice/924525bd4fb6.ogg",
  "Interlace all ten fingers and place the knuckles under the chin.": "/voice/7a09338997f4.ogg",
  "It is only ten seconds — give it everything, then step out clean.": "/voice/d22e142cadfc.ogg",
  "Keep both hips level and squared to the side, back leg strong, both feet fully planted.": "/voice/a6658d023cc3.ogg",
  "Keep both hips level with the floor; do not let the lifted-leg hip roll open.": "/voice/5cd2b36b06f6.ogg",
  "Keep both knees locked and the thigh muscles lifted; straight legs are what make the stretch honest.": "/voice/ae70a3808e88.ogg",
  "Keep both shoulders level and the chest lifted; do not let the twist collapse you sideways.": "/voice/624efefa1a03.ogg",
  "Keep both shoulders relaxed on the floor and draw the elbows down toward the body; the pull comes from bending the arms.": "/voice/1746a77d1d8e.ogg",
  "Keep both shoulders squared forward; resist the pull that wants to twist your chest open to the side.": "/voice/7fd39d03b639.ogg",
  "Keep breathing. If the breath stops, you have gone past your edge — back off an inch and find it again.": "/voice/c4e095c9c717.ogg",
  "Keep pressing the folded knee down toward the standing knee; the hip opens a little more with every breath.": "/voice/ebe061c97613.ogg",
  "Keep the arms glued beside the ears, elbows locked, palms sealed in prayer.": "/voice/72f39b3869a1.ogg",
  "Keep the arms glued to the ears and the palms pressed together — the shoulders will burn, and that is the work.": "/voice/6b056cf2a525.ogg",
  "Keep the arms in one unbroken vertical line, pulling away from each other like a stretched cable.": "/voice/ca0e28b1208d.ogg",
  "Keep the arms level with the shoulders and reach out through the fingertips, palms facing the floor.": "/voice/e115014e1d19.ogg",
  "Keep the arms, wrists, and elbows touching in front of the chest.": "/voice/381a2a79c389.ogg",
  "Keep the body in one flat plane — chest open, no twisting forward or back, as if bending between two panes of glass.": "/voice/82b7b029b657.ogg",
  "Keep the chin pinned to the chest; the gentle pressure at the front of the throat is doing quiet work on the thyroid.": "/voice/55a951b258b0.ogg",
  "Keep the eyes gently open, gaze resting on the ceiling.": "/voice/3554d5589851.ogg",
  "Keep the eyes toward the ceiling so the arch travels through the entire spine.": "/voice/8c6d89ebd29d.ogg",
  "Keep the folded knee reaching toward level, hip staying open just as it was in Tree.": "/voice/1c158bbebf60.ogg",
  "Keep the forehead glued to the knees — if it loses contact, walk the knees closer to the head.": "/voice/9b9bc0bb7800.ogg",
  "Keep the grip firm on the outside of the feet — the hands never let go, the feet never stop kicking.": "/voice/9ff3479b54a1.ogg",
  "Keep the hips glued to the heels; the fold happens in front of you, not by lifting the seat.": "/voice/cf7c40d881c1.ogg",
  "Keep the hips square and the standing foot pointing straight ahead; the body stays stacked, not tilted.": "/voice/50fae77fa56d.ogg",
  "Keep the knees together and on the floor; if they lift, that is your depth for today — stay on your elbows.": "/voice/464b1c715b83.ogg",
  "Keep the knuckles glued under the chin — the chin presses down as the elbows rise.": "/voice/21dc19d5e0bb.ogg",
  "Keep the legs glued together with the knees straight — two legs working as one tail.": "/voice/b549fa48dd77.ogg",
  "Keep the legs straight and the heels on the floor the whole way up — momentum is allowed, collapsing is not.": "/voice/710bfd2730be.ogg",
  "Keep the lifted leg completely straight — knee locked, the whole leg moving as one piece from the hip.": "/voice/0b63914286e5.ogg",
  "Keep the reaching arm alongside your ear and stretch your fingertips toward the mirror.": "/voice/62524ed6e36a.ogg",
  "Keep the rhythm even, like a metronome — one clean beat per exhale, sixty beats per set.": "/voice/2183ed216f99.ogg",
  "Keep the spine tall and the chest lifted; do not collapse over the fingertips.": "/voice/a743326c8ae7.ogg",
  "Keep the spine upright and the shoulders stacked over the hips — resist the pull to pitch forward.": "/voice/3f93a822b246.ogg",
  "Keep the weight even in both legs — the straight leg presses through the outer edge of its foot and works just as hard as the bent one.": "/voice/1ef9f94aa48e.ogg",
  "Keeping both arms in one straight line, tip them like a wheel spoke: right fingertips reach down toward the floor between the big toe and second toe, left arm points straight up.": "/voice/5685ec08d51b.ogg",
  "Keeping both hips resting on the arms, inhale and lift the right leg straight up to about forty-five degrees; hold, lower, then repeat with the left.": "/voice/314d91ba8ffe.ogg",
  "Keeping the arms straight and the hips on the heels, hinge forward from the hips in one piece.": "/voice/d03c4b2678de.ogg",
  "Keeping the grip, round forward slowly until the crown of the head touches the floor and the forehead touches the knees.": "/voice/52c79f2f3fba.ogg",
  "Kick and reach at the same time — the kick backward and the reach forward balance each other like two ends of a drawn bow.": "/voice/2c5d6677cbe6.ogg",
  "Kick both legs evenly so the spine bends as one smooth arc, not in pieces.": "/voice/ad0aa2e5f44d.ogg",
  "Kneel on the floor with your knees together and your feet apart, alongside your hips.": "/voice/68c5cccc5d19.ogg",
  "Kneel upright with the knees and feet about six inches apart, toes pointing straight back.": "/voice/c5635d943da2.ogg",
  "Kneel with your knees and feet together and sit back on your heels.": "/voice/1b098c4f45d3.ogg",
  "Knees together — slow motion down, slow motion up.": "/voice/45c15bf3e6e6.ogg",
  "Lean back onto one elbow, then the other, going down in stages.": "/voice/eee69c01a1fa.ogg",
  "Let only the pinky edges of the hands and the forehead rest on the floor — then stretch forward from the shoulders to lengthen the spine.": "/voice/587b951384df.ogg",
  "Let the chest lift and the breath soften; the lower you settle, the quieter the posture becomes.": "/voice/ad1f301450ef.ogg",
  "Let the floor take your full weight; scan for gripping in the jaw, shoulders, hands, and hips, and let each one go.": "/voice/385481740fe1.ogg",
  "Let the head drop all the way back, then reach one hand at a time down to grip each heel.": "/voice/a6d2847bc793.ogg",
  "Let the head hang fully back and the throat open; soften the jaw.": "/voice/4550b491898e.ogg",
  "Let the heels touch lightly and the feet fall open to the sides.": "/voice/581098c69759.ogg",
  "Let the kick roll your weight forward onto the soft part of the abdomen.": "/voice/c648f6915e23.ogg",
  "Let the kick, not gravity, bring your body down; aim the abdomen toward parallel with the floor.": "/voice/85c02c4fbb17.ogg",
  "Let the shoulders release toward the floor and the breath slow; this is a posture for resting deeply, not striving.": "/voice/801a779fe203.ogg",
  "Let the whole spine stay long — back of the neck soft, tailbone heavy, low back melting into the mat.": "/voice/7881a6cfbe06.ogg",
  "Lie face down with the chin reaching forward along the floor.": "/voice/c915a48cf66e.ogg",
  "Lie flat on your back with the legs extended along the floor.": "/voice/e9f945e5d8e1.ogg",
  "Lie flat on your back with the legs extended and the heels together.": "/voice/4b947275f6a8.ogg",
  "Lie on your abdomen and bend both knees.": "/voice/bb2e2db9d46d.ogg",
  "Lie on your abdomen with your chin stretched forward on the floor.": "/voice/20ecf1507e89.ogg",
  "Lie on your stomach, chin on the floor, legs together — hips, thighs, and the tops of the feet all pressing down.": "/voice/90f8adb69560.ogg",
  "Lift the chest and look up toward the ceiling; the head follows the rising sternum.": "/voice/85b02476efe0.ogg",
  "Lift the chest up toward the ceiling rather than collapsing back — think of arching over a barrel, not folding at one hinge.": "/voice/a86ac02a34f9.ogg",
  "Lift the chest, press the hips forward, and begin arching the upper spine back.": "/voice/77eb2e1cd037.ogg",
  "Lift the hips high and roll forward, stretching the spine one vertebra at a time from tailbone to neck.": "/voice/e3a6a0d1f6f0.ogg",
  "Lift the hips toward the ceiling, rolling forward like a wheel until the arms are straight.": "/voice/6f3f7a3d2eb2.ogg",
  "Lift the other knee and interlace all ten fingers under the ball of the flexed foot, thumbs with the fingers.": "/voice/245d1163e951.ogg",
  "Lock the elbows and squeeze the arms in tight against the ears — head, arms, and torso become one solid piece.": "/voice/7490145450cd.ogg",
  "Lock the standing knee and keep the standing leg like a steel pillar.": "/voice/c47a05f08930.ogg",
  "Lock the standing knee — the standing leg is a lamp post, solid from foot to hip.": "/voice/1c36f2f653ee.ogg",
  "Look forward and up; let the head follow the lifting chest.": "/voice/50aa01a3f45b.ogg",
  "Look up toward the ceiling, then inhale and curl the chest off the floor.": "/voice/f5cef289145a.ogg",
  "Lower until the sides of the pinky fingers and the forehead touch the floor.": "/voice/b9ce21705d1b.ogg",
  "Lying on your back, straighten both legs and flex the feet back toward your face.": "/voice/725d5c72ac1c.ogg",
  "Make the forward stretch quick and light; this is a transition, not a long hold.": "/voice/edff9b615620.ogg",
  "Move down and up as one solid unit — arms, head, and torso travel together with the spine long.": "/voice/69b699a7cf26.ogg",
  "Normal breathing throughout — steady and even. The burn will tempt you to hold the breath; instead let each slow exhale settle you deeper into the sit.": "/voice/0abc92d90d29.ogg",
  "Normal, continuous breathing in every part — no breath-holding in the side bends or backbend, and keep slow, steady breaths flowing even when folded flat against the legs.": "/voice/280c83afda08.ogg",
  "Normal, easy breathing throughout. Each exhale is an invitation — let the thigh settle a little deeper into the body every time the breath leaves.": "/voice/4e0feacff0f3.ogg",
  "On an inhale, kick your legs up and back, lifting chest and thighs off the floor together.": "/voice/1b8999e689c9.ogg",
  "On an inhale, lift arms, head, chest, and legs off the floor in one motion.": "/voice/df7933e0aa2c.ogg",
  "On the second side, everything mirrors: left arm under, left leg on top.": "/voice/9b70ed15d116.ogg",
  "Once forehead and knee are connected, slowly work the front leg toward straight without ever losing the touch.": "/voice/00e62bce00cd.ogg",
  "Only the abdomen moves; chest, shoulders, and face stay completely still and soft.": "/voice/f9842942b494.ogg",
  "Only the lightest touch of the crown on the floor; your arms carry the load, not your neck.": "/voice/ddd2a4bda657.ogg",
  "Only when the standing knee stays locked, begin kicking the held leg forward until it is straight and parallel to the floor, heel pushing away.": "/voice/b96ba8cae991.ogg",
  "Other side — come down slowly, spine tall, hands floating to prayer.": "/voice/739194f0d754.ogg",
  "Other side — grip the left ankle, right arm up.": "/voice/f4f271e8d0ae.ogg",
  "Other side — left arm under, left leg over the top.": "/voice/6e7c49b93c96.ogg",
  "Other side — left knee bends, arms tip the other way, eyes on the top hand.": "/voice/5fbc52f9fc56.ogg",
  "Other side — pivot the feet, square off over the left leg, and round down.": "/voice/c1b7866415e2.ogg",
  "Other side — stand on the right leg, lock the knee, and pick up the left foot.": "/voice/4ad73adffb66.ogg",
  "Other side — stand tall on the right leg, left foot up, palms to prayer.": "/voice/90b0f84b991f.ogg",
  "Other side — step forward and tip, one straight line.": "/voice/26bb59baa747.ogg",
  "Other side — ten seconds, everything you have.": "/voice/18708c8ee8e7.ogg",
  "Other side — twist to the left, look over the left shoulder.": "/voice/b30ea577ddd3.ogg",
  "Other side.": "/voice/286af4ee31f4.ogg",
  "Part one: keeping the chest lifted, bend the knees and sit the hips down and back as if into a chair, thighs working toward parallel with the floor.": "/voice/abc907714d8f.ogg",
  "Part three: heels up, knees and thighs squeezed together, and lower in slow motion until you hover just above the heels — then rise just as slowly.": "/voice/d60b80417a1c.ogg",
  "Part two: come up, rise as high as possible onto the toes, then sit again until the thighs are parallel to the floor.": "/voice/c8648f4f79a6.ogg",
  "Pick one point for your eyes and refuse to leave it — the concentration is not a means to the posture, it is the posture.": "/voice/ffa4e303347b.ogg",
  "Place the palms flat on the floor directly beneath the shoulders, fingertips in line with the tops of the shoulders.": "/voice/c8ecb4ffa6a8.ogg",
  "Place the right hand on the floor behind you, close to the spine.": "/voice/7943e8c47c37.ogg",
  "Place your hands on the back of your hips, fingers pointing down, and draw the elbows toward each other.": "/voice/6e2851f13e63.ogg",
  "Posture 10. Standing Separate Leg Head to Knee Pose.": "/voice/9553abb562ee.ogg",
  "Posture 11. Tree Pose.": "/voice/cc560706d206.ogg",
  "Posture 12. Toe Stand Pose.": "/voice/8c4f20b7690a.ogg",
  "Posture 13. Dead Body Pose.": "/voice/e8997f0a0cd4.ogg",
  "Posture 14. Wind-Removing Pose.": "/voice/4e1e757e5547.ogg",
  "Posture 15. Sit-Up.": "/voice/e841fbc2480a.ogg",
  "Posture 16. Cobra Pose.": "/voice/3e3b30f964be.ogg",
  "Posture 17. Locust Pose.": "/voice/db03fa598cff.ogg",
  "Posture 18. Full Locust Pose.": "/voice/9aff3b684e55.ogg",
  "Posture 19. Bow Pose.": "/voice/2b406de5d4e5.ogg",
  "Posture 2. Half Moon Pose with Hands to Feet Pose.": "/voice/251b73d06074.ogg",
  "Posture 20. Fixed Firm Pose.": "/voice/d241f12e0a05.ogg",
  "Posture 21. Half Tortoise Pose.": "/voice/b0f9d08510af.ogg",
  "Posture 22. Camel Pose.": "/voice/5039ae1434a0.ogg",
  "Posture 23. Rabbit Pose.": "/voice/ea05156197df.ogg",
  "Posture 24. Head to Knee Pose with Stretching Pose.": "/voice/877598970fcc.ogg",
  "Posture 25. Spine-Twisting Pose.": "/voice/8737997dae84.ogg",
  "Posture 3. Awkward Pose.": "/voice/f4912462ed75.ogg",
  "Posture 4. Eagle Pose.": "/voice/1988d00eb89f.ogg",
  "Posture 5. Standing Head to Knee Pose.": "/voice/8a6abf8bf458.ogg",
  "Posture 6. Standing Bow Pulling Pose.": "/voice/df006ca8a3ab.ogg",
  "Posture 7. Balancing Stick Pose.": "/voice/4d4e4704414b.ogg",
  "Posture 8. Standing Separate Leg Stretching Pose.": "/voice/b260e9628a3f.ogg",
  "Posture 9. Triangle Pose.": "/voice/0a56cb51e1fa.ogg",
  "Press the folded knee down toward the floor while keeping both hips level and facing forward.": "/voice/fe6ab41d92cf.ogg",
  "Pull hard on the heels the entire time — that pull is what keeps the weight off your head and neck.": "/voice/19e15c679da7.ogg",
  "Pull on the heels and draw the crown of the head down toward the floor.": "/voice/0b18d35465f5.ogg",
  "Pull the belly in and up — you are folding the body in half and wringing out the abdomen.": "/voice/8b8968db2e20.ogg",
  "Pull the crossed elbows down toward the waist while the fingers lift, so the stretch travels between the shoulder blades.": "/voice/e6c1cc1d2b9f.ogg",
  "Pull the elbows down and sit the hips low, as if into a chair.": "/voice/309a4e47897d.ogg",
  "Pull the knee down toward the right shoulder — beside the ribcage, not the center of the chest — while the left leg stays straight and heavy on the floor.": "/voice/54977927b982.ogg",
  "Pull the toes back toward you and press the heel away; the whole back line of the leg wakes up.": "/voice/1bfbc08fceb5.ogg",
  "Pull, hinge from the hips, and lay the belly down the thighs, reaching the face beyond the knees and the elbows toward the floor.": "/voice/ab7a545de04a.ogg",
  "Quiet, steady breathing throughout — exhale as you sink, breathe evenly in the squat, and inhale as you rise. Holding the breath is the fastest way to fall.": "/voice/10f93e930df8.ogg",
  "Raise both arms overhead and press the palms together, crossing the thumbs, arms hugging the ears.": "/voice/0fe0c155e257.ogg",
  "Raise both arms overhead from the sides and press the palms together, thumbs crossed.": "/voice/a5fc96a63be8.ogg",
  "Raise both arms to shoulder height, palms facing down — arms parallel to the floor and to each other, fingers together.": "/voice/1db35be0e129.ogg",
  "Raise the left arm straight up beside the ear, fingertips reaching for the ceiling.": "/voice/72fdb4f081a9.ogg",
  "Reach back and grip each foot from the outside, about two inches below the toes, fingers and thumbs together.": "/voice/3b34eef38aa7.ogg",
  "Reach both arms straight out to the sides at shoulder level, palms facing down, like the wings of an airplane.": "/voice/8659feb2e9db.ogg",
  "Reach down and grip the heels from the outside, fingers wrapped under the heels, thumbs on the outer edges of the feet.": "/voice/f9f8afe6508f.ogg",
  "Reach the arms overhead, take hold of opposite elbows, and rest them on the floor behind you.": "/voice/b9c980b591f5.ogg",
  "Reach the right arm back and grip the inside of the right ankle — palm facing outward, all five fingers together around the ankle.": "/voice/01133749996e.ogg",
  "Release every muscle you can find — and then stop moving entirely.": "/voice/a9dbe90e34b2.ogg",
  "Rest the arms alongside the body, palms turned up, fingers softly curled.": "/voice/9e62022ea5d8.ogg",
  "Rest the hands on the tops of the knees, arms relaxed but straight.": "/voice/b6719e2ee39d.ogg",
  "Revolve the chest open toward the ceiling; the twist lives in the upper body while the hips stay low and steady.": "/voice/34afa0402ba8.ogg",
  "Rise onto the ball of the left foot and sink the hips down until you are sitting on the lifted left heel.": "/voice/c859e0e723ff.ogg",
  "Roll over onto the belly, chin forward on the towel.": "/voice/aa9626480641.ogg",
  "Roll the shoulders down away from the ears and reach the chest forward as much as up.": "/voice/6902cbda0d34.ogg",
  "Rotate from the bottom up: belly first, then ribs, then shoulders, and last of all the chin over the shoulder.": "/voice/21346bb3f614.ogg",
  "Second set — a little faster. Sixty more.": "/voice/f5aae07f2347.ogg",
  "Second set — arms out, and sit down.": "/voice/509697581470.ogg",
  "Second set — arms up, stretch, and over to the right.": "/voice/83c609ed99cc.ogg",
  "Second set — chin to chest, forehead to the knee. Right side.": "/voice/c73e9dc24fe0.ogg",
  "Second set — everything lifts at once, look up.": "/voice/1652e2a97db0.ogg",
  "Second set — fold forward, forehead down, hips on the heels.": "/voice/d24dd658eb9e.ogg",
  "Second set — grip the ankles, kick, and look up.": "/voice/1df67ab6aa9f.ogg",
  "Second set — hips forward the whole time, one hand to each heel.": "/voice/51489065a7f8.ogg",
  "Second set — kick back and stretch forward. Right leg.": "/voice/1fe9eb8b7105.ogg",
  "Second set — only as deep as the knees allow, arms overhead on the floor.": "/voice/6eb3f79b7afc.ogg",
  "Second set — palms down, chest up, legs heavy on the floor.": "/voice/e9858bcc69c6.ogg",
  "Second set — right knee to the chest.": "/voice/84ffb6c1abf9.ogg",
  "Second set — right leg again, thirty seconds. Standing knee locked.": "/voice/830ec3b1019f.ogg",
  "Second set — right leg, head to the knee.": "/voice/91e720382484.ogg",
  "Second set — right leg, left leg, then both legs together.": "/voice/9178cce52270.ogg",
  "Second set — roll forward like a wheel, hips high, arms pulling.": "/voice/d94df392f908.ogg",
  "Second set — sink the hips low, arms one straight line. Right side.": "/voice/99bc20b4b1ea.ogg",
  "Second set — step forward, everything comes down together.": "/voice/772b6a6b1bc2.ogg",
  "Second set — step out wide, fold from the hips, and pull the forehead toward the floor.": "/voice/9fba212ff605.ogg",
  "Second set — ten more full breaths. Elbows high on the inhale, head back on the exhale.": "/voice/61263dfb1e13.ogg",
  "Second set — wrap the arms, sit down, and wrap the legs. Right side.": "/voice/c00d32d4e0ae.ogg",
  "Sensation of stretch in the thighs and ankles is the posture working; sharp pain in the knees means come up.": "/voice/3d7db3caa804.ogg",
  "Shaking thighs mean the posture is working, not failing; keep breathing and stay.": "/voice/b06ebacde185.ogg",
  "Shift the weight into the left leg, lift the right leg high over the left thigh, and hook the right foot behind the left calf.": "/voice/03019edfc410.ogg",
  "Shift your weight forward toward the toes — if the weight sits in the heels, the fold stalls.": "/voice/79966fd60334.ogg",
  "Shoulders draw away from the ears; the back of the neck stays long.": "/voice/155b160f09c5.ogg",
  "Sit and bend the left knee down to the floor, drawing the left heel beside the right hip.": "/voice/b65bb0e7db6c.ogg",
  "Sit and extend the right leg out at about forty-five degrees; bend the left knee and place the left sole against the right inner thigh.": "/voice/5d5b100f5e76.ogg",
  "Sit down between your heels, toes pointing straight back, feet hugging the hips.": "/voice/477286bbd862.ogg",
  "Sit lower than feels reasonable first — a deep sit makes the leg wrap possible, not the other way around.": "/voice/f04b15da1079.ogg",
  "Sit on your heels in Vajrasana — spine tall, shoulders relaxed, chest lifted.": "/voice/90c0402c3fb8.ogg",
  "Sit on your heels, then reach back and grip each heel firmly — thumbs on the outside, fingers on the inside.": "/voice/6897da132998.ogg",
  "Sit tall the whole time; a slumped spine muffles the pump.": "/voice/3bad60b33eca.ogg",
  "Sit-up — arms overhead, cross the thumbs, double exhale, and dive for the toes.": "/voice/2e8eda70ac90.ogg",
  "Sit-up.": "/voice/f5d0cf620a7a.ogg",
  "Six counts in through the nose with a soft throat friction, six counts out through the mouth with a \"ha\" sound from deep in the throat.": "/voice/788dcb96e355.ogg",
  "Slow, continuous breathing through the nose for the entire hold. Deep backbends tempt you to hold the breath — resist that; a steady breath is the proof you are working at the right depth.": "/voice/0e5ba49fd14c.ogg",
  "Slow, deliberate normal breathing. The wrap compresses the chest, so each breath has to be intentional — let that constraint make the breathing calmer, not shallower.": "/voice/9602cd7978b9.ogg",
  "Slow, even breathing throughout — send the inhale into the belly and chest as the front of the hips stretches, and let each exhale release you a little deeper.": "/voice/5759cef77b3b.ogg",
  "Slow, quiet, natural breathing — let each exhale sink you into stillness. This is the resting posture of the floor series; the breath should sound like sleep.": "/voice/460118e48123.ogg",
  "Smooth, unhurried breathing through the nose. Balance rides on the breath — the moment it turns choppy, the tree starts to sway, so keep it long and even.": "/voice/24c083ae3f5b.ogg",
  "Soften the belly so the thigh can actually sink into it — gripping the abdomen defeats the massage.": "/voice/992a46a38717.ogg",
  "Square the torso over the extended leg and interlace your fingers around the ball of the right foot, thumbs and fingers wrapped below the toes.": "/voice/60497e921225.ogg",
  "Squeeze everything toward the midline: forearms twisted, thighs sealed, no daylight anywhere between the limbs.": "/voice/78c145ccdd95.ogg",
  "Squeeze the glutes and press the thighs and tops of the feet down — the anchored lower body protects the low back.": "/voice/32ceadd6ed52.ogg",
  "Squeeze the glutes the whole time; they are the guardians of your lower back in this depth.": "/voice/12160988ef67.ogg",
  "Stand tall and shift your full weight onto the left leg, locking the knee.": "/voice/63dba782a3b8.ogg",
  "Stand tall through the crown of the head — no leaning, no sinking; the spine stays as straight as the trunk of a tree.": "/voice/ad24ca9274e9.ogg",
  "Stand tall, pour your weight into the left foot, and fix your gaze on one unmoving point ahead.": "/voice/caeb1b0a0520.ogg",
  "Stand with feet together, heels and toes touching.": "/voice/49a584eb7633.ogg",
  "Stand with feet together; sweep the arms up sideways over the head and interlace the fingers, releasing the index fingers into a steeple grip.": "/voice/b40867b593fd.ogg",
  "Standing Deep Breathing.": "/voice/0041ac13f891.ogg",
  "Stay tall on both sitting bones — a twist only works on a lengthened spine, so grow up out of the pelvis first.": "/voice/b6a137407afe.ogg",
  "Steady, continuous breathing through the nose. The deeper the kick, the calmer the breath needs to be — holding it will tip you over.": "/voice/9e44c9d94f75.ogg",
  "Steady, unbroken normal breathing. The effort will bait you into holding your breath — instead exhale slowly as you kick out, and again as you curl the spine down toward the knee.": "/voice/4688646f22dc.ogg",
  "Step or lightly hop the feet wide apart — roughly four feet, toes turned slightly inward.": "/voice/854954ede465.ogg",
  "Step the feet hip-width apart, toes and heels in two parallel lines.": "/voice/2a296d45386a.ogg",
  "Step the right foot about four feet to the right, then pivot both feet and square the hips and torso to face over the right leg.": "/voice/733cd83fb391.ogg",
  "Step the right foot one big step forward.": "/voice/f42cadb27d32.ogg",
  "Step the right foot over the left knee and plant it flat on the floor.": "/voice/7e3e6ed0a518.ogg",
  "Still eyes, still body, quiet breath. The posture is won by not moving.": "/voice/fa81fcb4d743.ogg",
  "Stillness is the posture. No fidgeting, no wiping sweat, no adjusting — every movement restarts the clock in your nervous system.": "/voice/e6933625dc1e.ogg",
  "Stop when everything is level: fingertips, spine, and lifted heel in one line parallel to the floor.": "/voice/67430d4b67f1.ogg",
  "Stretch in two directions at once: reach forward through the arms, push back through the lifted heel.": "/voice/2abe46aa1826.ogg",
  "Stretch the arms out to the sides at shoulder height, then hinge forward from the hips with a flat back.": "/voice/e4571a84308d.ogg",
  "Stretch the whole body up toward the ceiling and fix your gaze forward.": "/voice/098217ae10ec.ogg",
  "Stretch up toward the ceiling to lengthen out of the waist, then push the hips left and bend the whole upper body to the right; repeat on the other side.": "/voice/aff927874b6f.ogg",
  "Sweep the arms overhead onto the floor behind you and cross the thumbs.": "/voice/3ed91ddc967a.ogg",
  "Swing the arms out wide, then cross the right arm under the left at the elbows.": "/voice/7919340c84d3.ogg",
  "Take one easy full breath in and out to settle, then begin the rhythm.": "/voice/ba81cd5e5401.ogg",
  "The arms never drop — shoulder height, parallel to the floor, from the first sit to the last.": "/voice/99b5790b6a0c.ogg",
  "The belly is compressed, so the breath naturally shortens — keep it moving in a steady rhythm and never hold it while you kick.": "/voice/39c3f122a73a.ogg",
  "The bent knee tracks over the toes; do not let it collapse inward or drift past the ankle.": "/voice/a7924a3b304a.ogg",
  "The both-legs lift is a strength move, not a swing — press the palms down and lift from the glutes and low back in one unit.": "/voice/d19dcf61d901.ogg",
  "The chest and belly are compressed, so breathe into the back of the ribs — slow, deliberate breaths. Use each exhale to curl a fraction deeper into the ball.": "/voice/8c970020082a.ogg",
  "The chin stays glued to the chest so the head rides the movement instead of whipping it.": "/voice/4997e64a71b2.ogg",
  "The chin stays on the floor, stretching forward — a long neck keeps the work in the spine, not the shoulders.": "/voice/98570cead279.ogg",
  "The class is complete. Lie back into savasana, let the breath go, and stay for two minutes.": "/voice/e06201547bf5.ogg",
  "The extended leg works too: keep it actively straight, calf reaching for the floor, toes toward your face.": "/voice/0bcd610e80f0.ogg",
  "The feet stay glued alongside the hips, toes pointing straight back, soles facing the ceiling.": "/voice/5c18a221183e.ogg",
  "The fingertip only touches the floor — no weight in the hand; the legs carry everything.": "/voice/f322e3aa6a86.ogg",
  "The fingertips are training wheels — make them lighter, then lift one hand, then the other.": "/voice/9cf6eb5ee3a0.ogg",
  "The hips lead, not the head — press the thighs forward so they stay as vertical as you can manage.": "/voice/5c1c67cc3798.ogg",
  "The knee on the floor stays down — that anchor is what makes the twist travel through the spine instead of the hips.": "/voice/3a07fed70b84.ogg",
  "The legs do the work — kick up and back into your own hands and let the arms trail behind like straps on a bow.": "/voice/207f11a19dfc.ogg",
  "The lift belongs to the back muscles — keep the weight out of the hands until the palms could almost float off the floor.": "/voice/326e96323a5f.ogg",
  "The locked standing knee is the entire posture — if it bends, come out with grace and begin again.": "/voice/01423785ad73.ogg",
  "The position squeezes the chest, so the breaths will be short; keep them coming anyway.": "/voice/686db779d8f6.ogg",
  "The pressure on the forearms and elbows is intense and it is supposed to be there; adjust the arm position by small degrees rather than pulling the arms out.": "/voice/4e4ab3dda5c0.ogg",
  "The second set goes faster — same sharpness, quicker tempo.": "/voice/37b71f89c9c9.ogg",
  "The standing knee stays locked — a solid, unbending lamp post underneath everything.": "/voice/31da46efb08b.ogg",
  "Think of the body as the bow and the arms as the bowstring: the harder the kick, the deeper the bend.": "/voice/2281efc9d546.ogg",
  "Think of your body as one solid stick from fingertips to heel — nothing sags, nothing bends.": "/voice/151547fa3282.ogg",
  "This exercise is the breath: sixty forceful exhalations per set, driven entirely by the abdominal wall, with passive automatic inhales between them. The exhale is the only active phase.": "/voice/95b724c23e0b.ogg",
  "Touch the forehead to the right knee — bend that knee as generously as you need to make contact.": "/voice/17a8d994d0e7.ogg",
  "Tuck the chin firmly to the chest and round down slowly from the top of the spine, arms traveling with the head.": "/voice/e6989a2f0be0.ogg",
  "Tuck the chin firmly to the chest.": "/voice/160e57249296.ogg",
  "Tuck the chin tightly to the chest.": "/voice/43f097d5e5d9.ogg",
  "Tuck the chin toward the chest so the forehead, not the crown, reaches the floor.": "/voice/2e6d20e25da1.ogg",
  "Tuck the chin, round forward, and touch the forehead to the knee — bend the knee at first if you need to — then work the leg straight while the forehead stays down. Repeat on the left side.": "/voice/18999b9a62ae.ogg",
  "Turn the belly, chest, shoulders, and finally the head to the right. Then unwind and repeat the whole shape to the left.": "/voice/b7f0ecb2fc60.ogg",
  "Turn the head and set your gaze on the top hand.": "/voice/0ed9797a21c0.ogg",
  "Turn the right foot out ninety degrees; keep the left foot planted and the left leg straight.": "/voice/bee1a0461242.ogg",
  "Twenty-second savasana.": "/voice/2a8a80e4c8d4.ogg",
  "Twist the forearms around each other and press the palms flat together in front of the face, fingers pointing up below the nose.": "/voice/0b13423bd7cd.ogg",
  "Two exhales, every time: one as you come up to sitting, a second sharper one as you touch the toes.": "/voice/7ad61c48c764.ogg",
  "Up on the toes — and sit.": "/voice/c0de4380397e.ogg",
  "Use the arm against the knee as a gentle lever, not a crank — the spine does the twisting, the arm just keeps what you earn.": "/voice/fb264391420a.ogg",
  "Use the arm strength: pull steadily on the heels to draw the forehead closer to the floor.": "/voice/3255203115d9.ogg",
  "When the kick-out is steady, bend the elbows down toward the calf, then tuck the chin and slowly curl the forehead toward the knee.": "/voice/4023af561bd8.ogg",
  "When the mind replays the last posture or rehearses the next, return to the simple feeling of breath at the nostrils.": "/voice/6fccf8b86c87.ogg",
  "When you feel steady, release the foot and bring both palms together in prayer at the center of the chest.": "/voice/f3ebca74197f.ogg",
  "With both heels in hand, keep pushing the hips forward as the chest lifts toward the ceiling.": "/voice/3268a248b24c.ogg",
  "With every exhale, soften half an inch further — this is patient work, not a fight.": "/voice/c5f742969491.ogg",
  "Wobbling is part of the work — grip the floor with the standing foot, keep breathing, and rewrap if you fall out.": "/voice/aca9dd77e27e.ogg",
  "Work honestly for the full ten seconds — this posture is short because it asks for everything you have.": "/voice/b2f83f54ed4b.ogg",
  "Work the elbows toward each other until they are as close as possible under the abdomen.": "/voice/0f1779900a12.ogg",
  "Your eyes are the anchor: the gaze stays welded to that one spot on the floor from start to finish.": "/voice/850707cffc85.ogg",
};
